### ISSUE TITLE
A question for this project

### ISSUE THREAD

**Issue by rainingapple** [vegardit/copycat#1]
Hello , I am an undergraduate in CSU , and I'm interested in your project.

I forked your code , and I want to learn sync with your code

but I find that I need some parent dependences which is only in your own code.

This one :

<parent>
      <groupId>com.vegardit.maven</groupId>
      <artifactId>vegardit-maven-parent</artifactId>
      <version>RELEASE</version>
</parent>

I would be honored to have your help , and If it is not convenient for you, I won't disturb you any more.

**Comment by sebthom** [comment]
Hi, thanks for your interest in our project! The required artifacts are in Bintray's public [JCenter](https://bintray.com/bintray/jcenter) repository and not in Maven Central.

You just need to add this repository to your maven settings.xml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<settings>

  <profiles>
    <profile>
      <repositories>
        <repository>
          <id>central</id>
          <name>bintray</name>
          <url>https://jcenter.bintray.com</url>
          <snapshots><enabled>false</enabled></snapshots>
        </repository>
      </repositories>
    </profile>
  </profiles>

  <activeProfiles>
    <activeProfile>bintray</activeProfile>
  </activeProfiles>
</settings>
```

**Comment by rainingapple** [comment]
> Hi, thanks for your interest in our project! The required artifacts are in Bintray's public [JCenter](https://bintray.com/bintray/jcenter) repository and not in Maven Central.
> 
> You just need to add this repository to your maven settings.xml:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" ?>
> <settings>
> 
>   <profiles>
>     <profile>
>       <repositories>
>         <repository>
>           <id>central</id>
>           <name>bintray</name>
>           <url>https://jcenter.bintray.com</url>
>           <snapshots><enabled>false</enabled></snapshots>
>         </repository>
>       </repositories>
>     </profile>
>   </profiles>
> 
>   <activeProfiles>
>     <activeProfile>bintray</activeProfile>
>   </activeProfiles>
> </settings>
> ```

**Comment by rainingapple** [comment]
thanks
