### ISSUE TITLE
No release under releases

### ISSUE THREAD

**Issue by tanrak** [vegardit/copycat#82]
I would like to test (under Windows) this promising tool, but there is no binary release as described under [installation](https://github.com/vegardit/copycat#installation).

**Comment by sebthom** [comment]
I rerun the CI job, can you see the binaries now at https://github.com/vegardit/copycat/releases/tag/snapshot ?

**Comment by tanrak** [comment]
Yes, now i can see the downloads. Thank for the quick solution.
